name: CD

on:
  workflow_run:
      workflows: ['CI']
      types:
         - completed

    
jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /home/ubuntu/CampusFlow
            git pull origin main

            docker compose up -d --build
